### ISSUE TITLE
Strange result of "Forward only" mode

### ISSUE THREAD

**Issue by alexeytsv** [MiraGeoscience/geoapps#16]
I get strange values of **Forward only** mode for susceptibility model - wrong range and anomaly shape.
Reference model was result of scalar mag inversion.

**Comment by domfournier** [comment]
@alexeytsv Can you post an example for this?

**Comment by alexeytsv** [comment]
I've attached sample data with used json files for inversion and forward.

Regards,
Alexey

ср, 14 окт. 2020 г. в 20:56, domfournier <notifications@github.com>:

**Comment by alexeytsv** [comment]
@domfournier ,
Please find sample data with used json files for inversion and forward.
[test_fwd.zip](https://github.com/MiraGeoscience/geoapps/files/5380837/test_fwd.zip)

**Comment by alexeytsv** [comment]
There is also an error **ValueError** in the line 1260:
```
        mesh_object.add_data(
            {
                "Starting_model": {
                    "values": np.linalg.norm(
                        (activeCellsMap * model_map * mstart).reshape((3, -1)), axis=0
                    )[mesh._ubc_order],
                    "association": "CELL",
                }
            }
        )
```

**Comment by domfournier** [comment]
Right yes, thanks for flagging this again. I ran into the same issue.

**Comment by domfournier** [comment]
Currently the issue you have with the example posted is that the starting model is a constant value, and not the model you are trying to forward. 

Another issue we might address here is to avoid interpolation if not needed. We probably want to let the user select and existing Octree mesh rather than forcing to generate a new one. 

Although this more a new feature than a bug, let's keep this issue opened.

**Comment by alexeytsv** [comment]
Thank you,  @domfournier 
I admit my mistake in the parameters.
It's a good idea to use existing Octree mesh rather to generate a new one.
To use existing Octree mesh we need write new function like_octree_2_treemesh_ ? Or are there existing features?

**Comment by domfournier** [comment]
Will be covered on update to simpeg 0.14
