### ISSUE TITLE
various user files are written to the /assets/ dir in the code directories

### ISSUE THREAD

**Issue by craigmillernz** [MiraGeoscience/geoapps#19]
User and inversion generated files  and directories such as the SimPEG_PFInversion/ directory,  json, and zarr files are written to the /assets dir in the code base.

It would be preferable to have these files saved in the same dir as the input geoh5 file rather than in the code directory structure.

@domfournier

**Comment by domfournier** [comment]
Great idea @craigmillernz 
I can even add a folder selection widget, defaulting to the geoh5 director

**Comment by domfournier** [comment]
Implemented on branch #7
