### ISSUE TITLE
coordinate transformation doc info incorrect

### ISSUE THREAD

**Issue by carpatgon** [MiraGeoscience/geoapps#30]
Looking at the docs for the coordinate transformation geoapp: https://geoapps.readthedocs.io/en/latest/content/apps/coordinate_transformation.html 

The first sentence is referring to the export app rather than the coordinate transformation app. 
![image](https://user-images.githubusercontent.com/74015352/98276295-c1e27800-1f63-11eb-8c59-85dedb5344ee.png)

**Comment by domfournier** [comment]
Has been solved on #54
