### ISSUE TITLE
Set transferred data name

### ISSUE THREAD

**Issue by domfournier** [MiraGeoscience/geoapps#33]
Allow users to set the data name upon transfer using the Object to object interpolation app.
@orerocks request

**Comment by domfournier** [comment]
@orerocks

How would you like to deal with multi-select data?

**Comment by orerocks** [comment]
Not sure @domfournier. I tried to test what it does now, but it's crashing. I didn't realize multiselect was an option. I guess specifying a name only makes since if a single object is selected, so maybe ignore my request.

**Comment by domfournier** [comment]
I added the option of set the trailing flag...

**Comment by domfournier** [comment]
Feature added on PR #48
