### ISSUE TITLE
Update button crash

### ISSUE THREAD

**Issue by domfournier** [MiraGeoscience/geoapps#35]
Update crashes on path. Running from source pathed directory.

![image](https://user-images.githubusercontent.com/55204635/99296843-405cd680-27fc-11eb-92fb-f4e4f0e3b9a8.png)

@orerocks

**Comment by orerocks** [comment]
To be clear, update works when running Install_or_update.bat directly.

It only fails when I run the update from within the Index.ipynb homepage notebook.

**Comment by domfournier** [comment]
Button removed on #48
