### ISSUE TITLE
Erroneous replicate the list of norms and alpha values in pf_inversion.py

### ISSUE THREAD

**Issue by alexeytsv** [MiraGeoscience/geoapps#4]
We need to replicate the **norms** and **alphas** for vector inversion and get 12 values: 

>         if len(model_norms) == 4:
>             model_norms = model_norms * 3

Instead we multiply the values by 3 because model_norms is ndarray, not list. Cloning operator * works only for lists. But we convert list to ndarray:

>      model_norms =  np.c_[model_norms]

**Comment by domfournier** [comment]
You are very right! I was wondering why I couldn't replicate my old results.
Thank you for this.

**Comment by domfournier** [comment]
Will closed by PR #6
