### ISSUE TITLE
geoapps 0.9.0 can't run cells

### ISSUE THREAD

**Issue by craigmillernz** [MiraGeoscience/geoapps#425]
Hi team, thanks for the new release!
I'm having trouble getting cells to run.  I can launch the main application with Start_applications.bat and then launch the individual notebooks e.g. Grav and mag inversion.  However when I shift-enter on the first cell to start the applet it just sits there and never launches. This seems to occur for all the apps, I randomly tested a few.

Output from the prompt is below, main issue is perhaps

[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: aaa8fe63-b3a1-46b2-87e7-2ffe3de1875f

######

Start_applications.bat
conda 22.9.0
Using Conda: C:\Users\craigm\AppData\Local\miniforge3\condabin\conda.bat
[I 11:54:34.033 NotebookApp] Serving notebooks from local directory: C:\geoapps-main\geoapps
[I 11:54:34.033 NotebookApp] Jupyter Notebook 6.5.1 is running at:
[I 11:54:34.033 NotebookApp] http://localhost:8888/?token=ff05cdf74200d4078cb5d51c0afcefaafc08461f79de021e
[I 11:54:34.033 NotebookApp]  or http://127.0.0.1:8888/?token=ff05cdf74200d4078cb5d51c0afcefaafc08461f79de021e
[I 11:54:34.033 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:54:34.073 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/craigm/AppData/Roaming/jupyter/runtime/nbserver-12204-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=ff05cdf74200d4078cb5d51c0afcefaafc08461f79de021e
     or http://127.0.0.1:8888/?token=ff05cdf74200d4078cb5d51c0afcefaafc08461f79de021e
[E 11:54:35.767 NotebookApp] Could not open static file ''
[W 11:54:37.813 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (127.0.0.1) 31.240000ms referer=http://localhost:8888/notebooks/index.ipynb?token=ff05cdf74200d4078cb5d51c0afcefaafc08461f79de021e
[W 11:54:37.895 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (127.0.0.1) 0.000000ms referer=http://localhost:8888/notebooks/index.ipynb?token=ff05cdf74200d4078cb5d51c0afcefaafc08461f79de021e
[W 11:54:40.299 NotebookApp] Notebook index.ipynb is not trusted
[I 11:54:40.399 NotebookApp] 302 GET /notebooks/images/object_selection_thumbnail.png (127.0.0.1) 0.000000ms
[I 11:54:40.399 NotebookApp] 302 GET /notebooks/images/contours_thumbnail.png (127.0.0.1) 0.000000ms
[I 11:54:40.415 NotebookApp] 302 GET /notebooks/images/coordinate_transform_thumbnail.png (127.0.0.1) 15.620000ms
[I 11:54:40.415 NotebookApp] 302 GET /notebooks/images/data_interp_thumbnail.png (127.0.0.1) 15.620000ms
[I 11:54:40.415 NotebookApp] 302 GET /notebooks/images/model_surface.png (127.0.0.1) 0.000000ms
[I 11:54:40.421 NotebookApp] 302 GET /notebooks/images/export_thumbnail.png (127.0.0.1) 6.510000ms
[I 11:54:40.421 NotebookApp] 302 GET /notebooks/images/iso_surface.png (127.0.0.1) 6.510000ms
[I 11:54:40.421 NotebookApp] 302 GET /notebooks/images/scatter_thumbnail.png (127.0.0.1) 0.000000ms
[I 11:54:40.429 NotebookApp] 302 GET /notebooks/images/octree_mesh_creation.png (127.0.0.1) 8.280000ms
[I 11:54:40.431 NotebookApp] 302 GET /notebooks/images/block_model_and_object.png (127.0.0.1) 10.280000ms
[I 11:54:40.434 NotebookApp] 302 GET /notebooks/images/cluster_thumbnail.png (127.0.0.1) 2.000000ms
[I 11:54:40.435 NotebookApp] 302 GET /notebooks/images/peak_finder_parameters.png (127.0.0.1) 2.990000ms
[I 11:54:40.436 NotebookApp] 302 GET /notebooks/images/edge_detection_thumbnail.png (127.0.0.1) 3.990000ms
[I 11:54:40.466 NotebookApp] 302 GET /notebooks/images/inversion_grav_mag_thumbnail.png (127.0.0.1) 1.990000ms
[I 11:54:40.468 NotebookApp] 302 GET /notebooks/images/inversion_em1d_thumbnail.png (127.0.0.1) 2.000000ms
[I 11:54:40.469 NotebookApp] 302 GET /notebooks/images/inversion_dcip_thumbnail.png (127.0.0.1) 2.990000ms
[I 11:54:40.576 NotebookApp] Kernel started: d3d35a57-5b65-4841-b0b8-5d7e6802f502, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: aaa8fe63-b3a1-46b2-87e7-2ffe3de1875f
[W 11:54:56.605 NotebookApp] 404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (127.0.0.1) 0.000000ms referer=http://localhost:8888/notebooks/inversion/potential_fields/notebook.ipynb
[I 11:54:56.908 NotebookApp] 302 GET /notebooks/images/inversion_grav_mag_thumbnail.png (127.0.0.1) 1.450000ms
[I 11:54:56.977 NotebookApp] Kernel started: 5c1fa317-b3dd-4b24-a545-4156c832167e, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 8496cb6c-2dbd-404e-af42-4f76e08f69e1
[I 11:56:57.895 NotebookApp] Saving file at /inversion/potential_fields/notebook.ipynb

**Comment by craigmillernz** [comment]
Update this may be a browser issue.  Above error is with Firefox.  Trying again with Edge works (still takes a while to load, but does succeed, although with the same error and warning).

**Comment by domfournier** [comment]
Thanks for flagging. Let me look into it.

**Comment by domfournier** [comment]
@craigmillernz We are going to overall the app to use Dash in GEOPY-607. Maybe try using chrome until then?
