### ISSUE TITLE
 Number of cells in octree discretization

### ISSUE THREAD

**Issue by alexeytsv** [MiraGeoscience/geoapps#435]
Can anyone explain the need the number of cells along each dimension is in power of 2 for octree discretization?

**Comment by domfournier** [comment]
Certainly. Think of the 0th refinement as being a single (very large) cell. Any other refinement requires dividing those cells in 8 octants (divide by 2 along each dimension). So at the end if you were to count the number of cells along each axis (smallest refinement) in would always be a number 2^n. If what I am saying doesn't make sense, maybe this can help: https://en.wikipedia.org/wiki/Octree
