### ISSUE TITLE
Geoapps requires 'ipywidgets', 'osgeo' and 'discretize', which are not installed automatically

### ISSUE THREAD

**Issue by 1313e** [MiraGeoscience/geoapps#66]
The `geoapps` package requires the `ipywidgets`, `osgeo` and `discretize` packages, as attempted to be imported [here](https://github.com/MiraGeoscience/geoapps/blob/main/geoapps/export.py#L11-L18), but none of them are listed as requirements in the `setup.py` file.

Furthermore, `osgeo` is not an existing package on PyPI.
The only package that is there is empty, and thus nothing can be imported from it.
This means that `geoapps` cannot be imported.

**Comment by domfournier** [comment]
Thanks for this @1313e 

As a quick workaround, we can add those dependencies to the `environment.yml`, from which users can create a geoapps environment `conda env update --file environment.yml  --prune`

Would that be enough?

**Comment by 1313e** [comment]
That would work for now, yes!

**Comment by 1313e** [comment]
I just got back to this, and `osgeo` is a required package by `geoapps`, but is not declared in the `environment.yml` file.
Also, I checked, and it cannot be found on either conda(-forge) or PyPI.
So, at the moment, I still cannot use `geoapps`.

**Comment by domfournier** [comment]
`gdal/osgeo` are always difficult to install, mostly on windows machine. Hence why rely on `geopandas` to handle all those dependencies. 
Hard to tell why creating the environment from the `environment.yml` is so difficult on your side. Even `pytest` runs from it every time without issue, both on Windows and Linux.

**Comment by 1313e** [comment]
But I am currently running it on Linux, not on Windows.
And, the `environment.yml` file cannot be installed properly, somehow.

**Comment by 1313e** [comment]
Alright, I did get it to install (properly I think) after a lot of effort by  manually installing most packages one-by-one and ignoring some dependency conflicts.

**Comment by domfournier** [comment]
We've added `discretize`, `gdal` and `fiona` to the list of requirements in the `environment.yml`. 
@1313e good on your side?

**Comment by 1313e** [comment]
It seems to work better now.
