### ISSUE TITLE
Add "no data value" for air cells

### ISSUE THREAD

**Issue by craigmillernz** [MiraGeoscience/geoapps#8]
Currently air cells are given a value of 0.  This makes it harder to remove air cells as data may also have 0 values.  Can aircells be assigned the no data value?

**Comment by alexeytsv** [comment]
You can you use **no_data_value** term in json file for this. 
Simply add line 
`"no_data_value": -100,
`
for example

**Comment by craigmillernz** [comment]
Thanks for that.  This would be great to include as an option in the notebook as well.

**Comment by craigmillernz** [comment]
@domfournier if you are updating the inversion notebook could you please add the option to specify the no_data_value?
