### ISSUE TITLE
Add Colorbar to contouring app

### ISSUE THREAD

**Issue by ThomasMGeo** [MiraGeoscience/geoapps#92]
For the plot of the data, a colorbar and/or a histogram of the data would aid in contour selection.

**Comment by domfournier** [comment]
Implemented on #GEOPY-211

Works for you @ThomasMGeo ?
![colorbar](https://user-images.githubusercontent.com/55204635/121066119-66d56580-c77e-11eb-875d-9511229d42b3.gif)

**Comment by ThomasMGeo** [comment]
Looks great! Perfect. Thanks!

**Comment by domfournier** [comment]
Added on GEOPY-211
